### ISSUE TITLE
QGIS Plugin: Importing large data sets crashes QGIS

### ISSUE THREAD

**Issue by DennisLigtenberg** [sourcepole/ogrtools#11]
Importing large data sets into the QGIS layer crashes QGIS because of Memory problems. Importing the same Data directly into QGIS after converting it to shapefile works.

**Comment by pka** [comment]
Current version was successfully tested with cadastral datasets of middle sized cities. Please reopen with more information about data and plugin/QGIS versions if crash is reproducable.
