### ISSUE TITLE
Sonderzeichen / Encoding unter Windows/Linux:

### ISSUE THREAD

**Issue by rkrucker** [sourcepole/ogrtools#2]
Unter Windows und Linux gibt es Encoding-Probleme. Diese prägen sich auf den Plattformen unterschiedlich aus. Untenstehend einige Beispiele
- Windows: Latin1-XTF -> PostGIS (oder GML): "Bundesgesetz über die Raumplanung" -> "Bundesgesetz "
- Windows: UTF8-XTF -> PostGIS: "Bundesgesetz über die Raumplanung" -> leerer Datensatz mit skipfailure=TRUE
- Windows: UTF8-XTF -> GML: "Bundesgesetz über die Raumplanung" -> "Bundesgesetz ?ber die Raumplanung"
- Linux: Latin1-XTF -> PostGIS (oder GML): "Bundesgesetz über die Raumplanung" -> "Bundesgesetz "
- Linux: UTF8-XTF -> GML: "Bundesgesetz über die Raumplanung" -> "Bundesgesetz über die Raumplanung"

**Comment by Doemelti** [comment]
Habe dasselbe Problem unter Windows mit ITFs, welche UTF-8 codiert sind. Ich verwende das INTERLIS-Plugin in QGIS. Standardmässig wird dann der QGIS-Layer auf Codierung "System" gesetzt. Es wäre hilfreich, wenn es im Import-Dialog wenigstens die Option gäbe, das Encoding zu wählen, analog Textfile-Import: 
![image](https://user-images.githubusercontent.com/19473798/35224922-1380dd6e-ff87-11e7-921c-c7b9fdb784b7.png)
