### ISSUE TITLE
Fehlermeldungen nur in Python-Konsole

### ISSUE THREAD

**Issue by rkrucker** [sourcepole/ogrtools#3]
Verschiedene Fehlermeldungen werden nur in der Python-Konsole angezeigt. Entweder User auf fehlerhafe Eingaben aufmerksam machen oder Buttons disablen, bis gültige Eingaben erfolgen. 
Beispiele für solche Fehlermeldungen:
* Nicht existierendes imd-File bei Import angegeben
* Nicht existierendes imd-File bei Export angegeben

**Comment by pka** [comment]
In the meantime, messages are displayed in the message log.
